services:
  - type: web
    name: weather-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Weather_Predictor_Project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Weather_Predictor_Project.settings
      - key: PYTHON_VERSION
        value: 3.11
