version: 1
services:
  - type: web
    name: weather-predictor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn weather_project.wsgi:application
    routes:
      - type: static
        path: /static
        source: staticfiles  # Make sure this is where your static files are being collected
